Config changes to make most unit tests work on updated frameworks (4.…
tspence/csharp-csv-reader pull request #50
Opened 2022-12-06 19:08 UTC by rfreytag

…8.1)

Had to add NUnit3 references to get most of the tests to pass.  Pull request is to share this fix with others.  

*Cannot* execute src.netstandard20/tests.net50; which is supposed to call src.netstandard20/src.net50.  

The src.netstandard20/src.net50 compiles and links with other projects but does *not* execute when called by src.netstandards20/tests.net50.  Don't know why and don't know how to figure it out.  

I am running in Visual Studio Pro 17.3.6.  

Help getting src.netstandard20/tests.net50 to pass *much appreciated!*

2022-12-06 19:36 UTC, tspence commented
I think I may know why this is happening.  I originally built the project as Net50 and NetFramework separately; but eventually I found that NetStandard2.0 covered most of my use cases and I de-emphasized the Net50 built in favor of the NetStandard2.0 one.  Let me dig into this PR and see what I can spot.

2022-12-06 21:44 UTC, tspence commented
Hmm.  I looked at my last build, dated to April.  At that time, the build and test did succeed correctly on every environment, including Net50.  Here's the record of the build and test:

https://github.com/tspence/csharp-csv-reader/actions/runs/2092951891/jobs/3042580202

Are you seeing something different?

2022-12-07 18:03 UTC, rfreytag commented
Hi Ted,

Thanks for your reply.  

In what environment are you building?  I don't recognize the format of the compilation output you provided.  

I am building in VS Pro V17.3.6 and everything builds just fine.  The problem I had in my dev environment was that your previous version would not execute the tests; they would just show as "not executed" when I tried to run them.  

...then...

I added the NuGet package for NUnit3TestAdapter (v4.3.1) to the ../src/... projects: net20, net40, net45, net50, and netstandard20.  
NOTE that according to: [ https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter ]( https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter ) 
..."that VSIX test adapters will be deprecated in the upcoming Visual Studio 2019".  I am not sure but think this means VS v19 and higher will require NUnit3TestAdapter.  

I can tell you that after these changes all the tests ran and passed except those under test.net50.  

Of course, the only version I can use with my application happens to be src.net50 - of course.  ;-)
And the src.net50 DLL does work.  So I am mostly trying to solve this one little problem and offer a solution(?) to getting the other tests to run.  

Hoping this is helpful.  If not I'd sure like to learn how I'm wrong.  

Many thanks, either way,
Richard F. 
 
 
 
 
 
-----Original Message-----
From: "Ted Spence" ***@***.***>
Sent: Tuesday, December 6, 2022 4:44pm
To: "tspence/csharp-csv-reader" ***@***.***>
Cc: "rfreytag-fandco" ***@***.***>, "Author" ***@***.***>
Subject: Re: [tspence/csharp-csv-reader] Config changes to make most unit tests work on updated frameworks (4.… (PR #50)



Hmm. I looked at my last build, dated to April. At that time, the build and test did succeed correctly on every environment, including Net50. Here's the record of the build and test:
[ https://github.com/tspence/csharp-csv-reader/actions/runs/2092951891/jobs/3042580202 ]( https://github.com/tspence/csharp-csv-reader/actions/runs/2092951891/jobs/3042580202 )
Are you seeing something different?
—
Reply to this email directly, [ view it on GitHub ]( https://github.com/tspence/csharp-csv-reader/pull/50#issuecomment-1340050885 ), or [ unsubscribe ]( https://github.com/notifications/unsubscribe-auth/AAAESOERGNRLGR2WN7KCJUTWL6XVTANCNFSM6AAAAAASV4IB5I ).
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-07 18:07 UTC, rfreytag commented
...should have mentioned NUnit3TestAdapter (v4.3.1) to the tests/... projects to get most of the test to run and pass.

2022-12-07 18:52 UTC, tspence requested changes
After testing this locally, this looks good, except for the dotnet framework version changes.  Can you undo those?

I can verify that by adding the NUnit test adapter that VS 2022 can build and test things correctly using this approach.

![image](https://user-images.githubusercontent.com/1933486/206270174-7f51b03f-1366-46d8-988d-9f91f166d0b2.png)

2022-12-07 18:52 UTC, tspence commented on src/net20/src.net20.csproj
> +    <TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>
Hmm, this change is one I don't want to make.  I would prefer to have each test run in the correct framework version if possible; I've caught lots of weird bugs this way in the past.

2022-12-07 18:52 UTC, tspence commented on src/net40/src.net40.csproj
> +<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Hmm, I should also replace the old project files with SDK style ones.

2022-12-07 19:26 UTC, tspence commented on src/net40/src.net40.csproj
> +<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
This isn't necessary for this PR; I'll do it separately.

2022-12-08 17:58 UTC, tspence commented
In the interest of moving this forward, I'll merge this PR and fix the issues in it with a separate change.

2022-12-08 17:59 UTC, merged

2022-12-09 14:39 UTC, rfreytag commented on src/net20/src.net20.csproj
> +    <TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>
This was a hold-over from my trying various ways to attack the tests not running.  Eventually I hit on NUnit3 and Nunit3TestRunner.  Definitely want to unwind my Framework changes to stay compatible with v2.0, v4.0, and v4.5.  

As a note the .NET download page did not seem to have v2.0, among the out-of-date versions: [https://dotnet.microsoft.com/en-us/download/dotnet-framework](https://dotnet.microsoft.com/en-us/download/dotnet-framework).  

Just tried googling ".net framework 2.0" which turned up: [https://www.microsoft.com/en-us/download/details.aspx?id=6041](https://www.microsoft.com/en-us/download/details.aspx?id=6041).  

I didn't give that a try as I see you have taken the ball which is good.

2022-12-09 14:43 UTC, rfreytag commented
There is still the question of why tests/net50 tests would not execute and step through the src/net50 code.  But I imaging your other pull request will address this concern.

2022-12-09 16:54 UTC, rfreytag commented
Ted, would it have been better if I'd started with issuing a PR from a different working branch?